### ISSUE TITLE
IGN403: You have sent transactions from 0x... and they interfere with Hardhat Ignition. Please wait until they get 5 confirmations before running Hardhat Ignition again.

### ISSUE THREAD

**Issue by luiztools** [NomicFoundation/hardhat-ignition#725]
I'm trying to deploy a simple ERC-20 with OpenZeppelin Contracts example to BSC Testnet. RPC Node URL: https://data-seed-prebsc-1-s1.binance.org:8545/ and ChainID 97

I don't have any pending transaction in the wallet. I've tried many times, without success.

Locally (HardHat Network) it works fine. Full stack trace below (I've ommited my wallet address):

NomicLabsHardhatPluginError: IGN403: You have sent transactions from 0x... and they interfere with Hardhat Ignition. Please wait until they get 5 confirmations before running Hardhat Ignition again.
    at SimpleTaskDefinition.action (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/@nomicfoundation/hardhat-ignition/src/index.ts:250:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Environment._runTaskDefinition (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at async Environment.run (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at async main (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/hardhat/src/internal/cli/cli.ts:323:7)

    Caused by: IgnitionError: IGN403: You have sent transactions from 0x... and they interfere with Hardhat Ignition. Please wait until they get 5 confirmations before running Hardhat Ignition again.
        at getNonceSyncMessages (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/@nomicfoundation/ignition-core/src/internal/execution/nonce-management/get-nonce-sync-messages.ts:117:15)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async ExecutionEngine._syncNonces (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/@nomicfoundation/ignition-core/src/internal/execution/execution-engine.ts:219:31)
        at async ExecutionEngine.executeModule (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/@nomicfoundation/ignition-core/src/internal/execution/execution-engine.ts:70:23)
        at async Deployer.deploy (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/@nomicfoundation/ignition-core/src/internal/deployer.ts:194:25)
        at async SimpleTaskDefinition.action (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/@nomicfoundation/hardhat-ignition/src/index.ts:220:24)
        at async Environment._runTaskDefinition (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
        at async Environment.run (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
        at async main (/Users/luiztools/NodeProjects/web23-alunos/protocoin-bep20-hardhat/node_modules/hardhat/src/internal/cli/cli.ts:323:7)
luiztools@Luizs-MacBook-Pro protocoin-bep20-hardhat % npm run deploy:bsctest

**Comment by luiztools** [comment]
Edit: the same contract deploy to Sepolia over Infura works well too.

I've already tried to wipe previous deployment files and clear HardHat cache.

**Comment by luiztools** [comment]
> I am closing in preference to #665.
> 
> Could I ask you @luiztools whether the repo you are trying to deploy from is open source, or whether you can show us your Ignition module? I would be interested in how many on-chain interactions are involved in the deploy.

//ignition module
import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";

const ProtoCoinModule = buildModule("ProtoCoinModule", (m) => {
  const protocoin = m.contract("ProtoCoin");

  return { protocoin };
});

export default ProtoCoinModule;

//contract
pragma solidity ^0.8.24;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract ProtoCoin is ERC20 {
    constructor() ERC20("New ProtoCoin", "NPC") {
        _mint(msg.sender, 10000000 * 10**18);
    }
}

**Comment by PhatIT2003** [comment]
I have the same error as you, but I don't know how to fix it. I can't fix it

**Comment by l1135677068** [comment]
I have the same error as you, but I don't know how to fix it. 
I deployed my contract in Ethereum sepolia, here is my hardcat.config.ts
`
import { HardhatUserConfig } from "hardhat/config"
import "@nomicfoundation/hardhat-toolbox-viem"
import "dotenv/config" // 在代码里使用process.env 需要引入这个包

const SEPOLIA_RPC_URL = process.env.RPC_URL
const PRIVATE_KEY = process.env.PRIVATE_KEY!
console.log(PRIVATE_KEY, "chainId: 11155111")
const config: HardhatUserConfig = {
    // defaultNetwork: "hardhat",
    networks: {
        sepolia: {
            url: "https://eth-sepolia.g.alchemy.com/v2/huCbNpOIXrKyBMFW1rpnJvjzQSQD52SI",
            accounts: [PRIVATE_KEY],
            chainId: 11155111,
        },
    },
    solidity: "0.8.24",
}

export default config
`
can anyone help me fix this problem

**Comment by kofkuiper** [comment]
I set `requiredConfirmations` to 1, and it works for me🎉

```
const config: HardhatUserConfig = {
  solidity: "0.8.24",

  ignition: {
    requiredConfirmations: 1
  },
};
```

Here is my example repository using Hardhat Ignition: https://github.com/kofkuiper/hardhat-ignition-template

---
If you want to deploy a contract without using previous executions stored in the `.\ignition\deployments` folder, you can customize the deployment folder name by providing an explicit deployment ID with the `--deployment-id <id>` option.

example

```
npx hardhat ignition deploy ./ignition/modules/Lock.ts  --deployment-id "eth-1-prod"
```

**Comment by DennisChi** [comment]
> I set `requiredConfirmations` to 1 in hardhat.config file, and it works for me🎉
> 
> ```
> const config: HardhatUserConfig = {
>   solidity: "0.8.24",
> 
>   ignition: {
>     requiredConfirmations: 1
>   },
> };
> ```
> 
> Here is my example repository using Hardhat Ignition: https://github.com/kofkuiper/hardhat-ignition-template
> 
> If you want to deploy a contract without using previous executions stored in the `.\ignition\deployments` folder, you can customize the deployment folder name by providing an explicit deployment ID with the `--deployment-id <id>` option.
> 
> example
> 
> ```
> npx hardhat ignition deploy ./ignition/modules/Lock.ts  --deployment-id "eth-1-prod"
> ```

It doesn't work for me. It's strange that it works fine on Sepolia, but there are always errors on the BSC testnet.

**Comment by cxp-13** [comment]
> > I set `requiredConfirmations` to 1 in hardhat.config file, and it works for me🎉
> > ```
> > const config: HardhatUserConfig = {
> >   solidity: "0.8.24",
> > 
> >   ignition: {
> >     requiredConfirmations: 1
> >   },
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here is my example repository using Hardhat Ignition: https://github.com/kofkuiper/hardhat-ignition-template
> > If you want to deploy a contract without using previous executions stored in the `.\ignition\deployments` folder, you can customize the deployment folder name by providing an explicit deployment ID with the `--deployment-id <id>` option.
> > example
> > ```
> > npx hardhat ignition deploy ./ignition/modules/Lock.ts  --deployment-id "eth-1-prod"
> > ```
> 
> It doesn't work for me. It's strange that it works fine on Sepolia, but there are always errors on the BSC testnet.
I have meet the error at bsc testnet, but deploy on remix ide is work and verify plug-in does't work.

**Comment by ana0** [comment]
I have this too, on polygon using infura. My ignition module has no transactions in it but the contract deployment. The error appears after I run the ignition module and hardhat gives me an error that the transaction was not mined even with maximum gas fee. All future runs with the same deploy key cause this one

The error text is incorrect, this is a fresh key I have never used outside of hardhat and the nonce should be 0. The only transaction sent with it is through hardhat and hardhat should know that failed. What would be helpful is knowing where hardhat is caching it's nonce so I can set it manually/delete

**Comment by TomWang1** [comment]
i meet same trouble`IgnitionError: IGN403: You have sent transactions from 0xe5.... and they interfere with Hardhat Ignition. Please wait until they get 5 confirmations before running Hardhat Ignition again.
    at getNonceSyncMessages (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\nodhat Ignition. Please wait until they get 5 confirmations before running Hardhat Ignition again.
    at getNonceSyncMessages (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\nonce-management\get-nonce-sync-messages.ts:118:15)
    at getNonceSyncMessages (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\nonce-management\get-nonce-sync-messages.ts:118:15)
nce-management\get-nonce-sync-messages.ts:118:15)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:221:31)
    at ExecutionEngine.executeModule (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:71:23)
    at Deployer.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\deployer.ts:196:2    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:221:31)
    at ExecutionEngine.executeModule (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:71:23)
    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:221:31)
    at ExecutionEngine.executeModule (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\exe    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:221:31)
    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execu    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execu    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execu    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:221:31)
    at ExecutionEngine.executeModule (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:71:23)
    at Deployer.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\deployer.ts:196:2tion\execution-engine.ts:221:31)
    at ExecutionEngine.executeModule (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:71:23)
    at Deployer.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\deployer.ts:196:2    at ExecutionEngine.executeModule (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:71:23)
    at Deployer.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\deployer.ts:196:2cution\execution-engine.ts:71:23)
    at Deployer.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\deployer.ts:196:2    at Deployer.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\deployer.ts:196:25)
    at Proxy.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\hardhat-ignition-ethers\src\ethers-ignition-hel5)
    at Proxy.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\hardhat-ignition-ethers\src\ethers-ignition-helper.ts:154:20)
    at Proxy.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\hardhat-ignition-ethers\src\ethers-ignition-helper.ts:154:20)
    at deployToken (C:\Users\admin\Desktop\FTB\scripts\FTB.js:129:20)
per.ts:154:20)
    at deployToken (C:\Users\admin\Desktop\FTB\scripts\FTB.js:129:20)
    at deployToken (C:\Users\admin\Desktop\FTB\scripts\FTB.js:129:20)
    at main (C:\Users\admin\Desktop\FTB\scripts\FTB.js:6:3)`

**Comment by crypto-cooker** [comment]
Error in plugin hardhat-ignition: IGN403: You have sent transactions from 0x1b4ae5baf3c082002dd185665705e36b5f6cb68d and they interfere with Hardhat Ignition. Please wait until they get 1 confirmations before running Hardhat Ignition again.

For more info run Hardhat with --show-stack-traces
