### ISSUE TITLE
Hardhat keep show error Error in plugin hardhat-ignition: IGN403: You have sent transactions from 0x even on new machine 

### ISSUE THREAD

**Issue by duongvansang** [NomicFoundation/hardhat-ignition#780]
### What happened?

I deploy contract to BSC testnet with command:

` npx hardhat ignition deploy ignition/modules/script.js --network bsc_test --verify`

Somehow issue, and deployment is not go through, but the BIG issue is I have no way to redeploy it again, event I tried on new machine, it's properly Hardhat store my deployment information on hardhat server.

It is critical issue

### Minimal reproduction steps

1. Deploy contracts using archemy rpc
2. Stop, or cancel deployment
3. Never able to deploy again, even try on new project, machine

**Comment by kanej** [comment]
@duongvansang you will need to give more information:

* What error did you encounter when you first run the deployment?
* What error do you encounter when your run the deployment again?

**Comment by kanej** [comment]
> ### Hello, I have the same problem with this issue.
> 
> **At first run I get the error:** Batch #1 Executing DeployModule#FirstVaultStaking - bumping gas fee (2/4)... An unexpected error occurred: ProviderError: already known **at the 2nd run when I ran again:** An unexpected error occurred: ProviderError: replacement transaction underpriced **At the final:** Error in plugin hardhat-ignition: IGN403: You have sent transactions from 0x and they interfere with Hardhat Ignition. Please wait until they get 5 confirmations before running Hardhat Ignition again. How to fix pls

What chain are you running on?

**Comment by kanej** [comment]
I am closing for the now. We will reopen if we get more information.

**Comment by TomWang1** [comment]
IgnitionError: IGN403: You have sent transactions from 0x......... and they interfere with Hardhat Ignition. Please wait until they get 5 confirmations before running Hardhat Ignition again.
    at getNonceSyncMessages (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\nonce-management\get-nonce-sync-messages.ts:118:15)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:221:31)
    at ExecutionEngine.executeModule (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:71:23)
    at Deployer.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\deployer.ts:196:25)
    at Proxy.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\hardhat-ignition-ethers\src\ethers-ignition-helper.ts:154:20)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:221:31)
    at ExecutionEngine.executeModule (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:71:23)
    at Deployer.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\deployer.ts:196:2    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:221:31)
    at ExecutionEngine.executeModule (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\exe    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:221:31)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execu    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at ExecutionEngine._syncNonces (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:221:31)
    at ExecutionEngine.executeModule (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\execution\execution-engine.ts:71:23)
    at Deployer.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\ignition-core\src\internal\deployer.ts:196:25)
    at Proxy.deploy (C:\Users\admin\Desktop\FTB\node_modules\@nomicfoundation\hardhat-ignition-ethers\src\ethers-ignition-helper.ts:154:20)
    at deployToken (C:\Users\admin\Desktop\FTB\scripts\FTB.js:129:20)
    at main (C:\Users\admin\Desktop\FTB\scripts\FTB.js:6:3)

**Comment by Kidkender** [comment]
@TomWang1 
You should increase the amount of deploy gas or increase the transaction nonce number. If it still doesn't work, you can try deleting the pending transaction.

**Comment by TomWang1** [comment]
> > ### Hello, I have the same problem with this issue.
> > **At first run I get the error:** Batch [#1](https://github.com/NomicFoundation/hardhat-ignition/issues/1) Executing DeployModule#FirstVaultStaking - bumping gas fee (2/4)... An unexpected error occurred: ProviderError: already known **at the 2nd run when I ran again:** An unexpected error occurred: ProviderError: replacement transaction underpriced **At the final:** Error in plugin hardhat-ignition: IGN403: You have sent transactions from 0x and they interfere with Hardhat Ignition. Please wait until they get 5 confirmations before running Hardhat Ignition again. How to fix pls
> 
> What chain are you running on?

bsctest   chainid : 97

**Comment by TomWang1** [comment]
> [@TomWang1](https://github.com/TomWang1) You should increase the amount of deploy gas or increase the transaction nonce number. If it still doesn't work, you can try deleting the pending transaction.
 it still doesn't work

**Comment by TomWang1** [comment]
> [@TomWang1](https://github.com/TomWang1) You should increase the amount of deploy gas or increase the transaction nonce number. If it still doesn't work, you can try deleting the pending transaction.

 it still doesn't work

**Comment by Kidkender** [comment]
@TomWang1 
For bsc chain, follow these steps:

- In hardhat config add retry = 3 and increase gas price 
- Use ignition wipe to clear tx and try deploying again
- Change the rpc node and use another account that has not been used before and deploy again.

I have encountered the same thing before with bsc chain

**Comment by tezhm** [comment]
I was encountering:

```
Error in plugin hardhat-ignition: IGN403: You have sent transactions from 0xblah and they interfere with Hardhat Ignition. Please wait until they get 5 confirmations before running Hardhat Ignition again.
```

Turned out my local optimism node was frozen. Had to nuke the node and then everything started working again. This wouldn't be plausible on a test net or main net, but if you're developing locally this might help you.
